// 教官/学员前端使用的页面权限常量（管理员专属页面已排除）

export const DASHBOARD_PERMISSIONS = ['GET_DASHBOARD']
export const TRAINING_PERMISSIONS = ['GET_TRAININGS', 'GET_TRAINING_DETAIL']
export const TRAINING_SCHEDULE_PERMISSIONS = ['GET_TRAINING_SCHEDULE']
export const EXAM_LIST_PERMISSIONS = ['GET_EXAMS', 'SUBMIT_EXAM', 'GET_EXAM_RESULT']
export const RESOURCE_LIBRARY_PERMISSIONS = ['GET_RESOURCES']
export const MY_RESOURCE_PERMISSIONS = ['CREATE_RESOURCE', 'UPDATE_RESOURCE', 'SUBMIT_RESOURCE_REVIEW']
export const PROFILE_PERMISSIONS: string[] = [] // 所有已登录用户可访问
