// 教官/学员前端使用的页面权限常量（管理员专属页面已排除）

export const DASHBOARD_PERMISSIONS = ['GET_DASHBOARD']
export const TRAINING_PERMISSIONS = ['GET_TRAININGS', 'GET_TRAINING_DETAIL']
export const TRAINING_SCHEDULE_PERMISSIONS = ['GET_TRAINING_SCHEDULE']
export const EXAM_LIST_PERMISSIONS = ['GET_EXAMS', 'SUBMIT_EXAM', 'GET_EXAM_RESULT']
export const COURSE_PERMISSIONS = ['GET_COURSES', 'GET_COURSE_DETAIL']
export const RESOURCE_LIBRARY_PERMISSIONS = ['GET_RESOURCES']
export const MY_RESOURCE_PERMISSIONS = ['CREATE_RESOURCE', 'UPDATE_RESOURCE', 'SUBMIT_RESOURCE_REVIEW']
export const TEACHING_RESOURCE_GENERATION_PERMISSIONS = ['USE_TEACHING_RESOURCE_GENERATION']
export const REPORT_PERMISSIONS = [
  'GET_REPORT_KPI',
  'GET_REPORT_TREND',
  'GET_POLICE_TYPE_DIST',
  'GET_CITY_RANKING',
]
export const SCOPE_USER_PERMISSIONS = ['GET_USERS']
export const SCOPE_DEPARTMENT_PERMISSIONS = ['GET_DEPARTMENTS']
export const SCOPE_ROLE_PERMISSIONS = ['GET_ROLES']
export const PROFILE_PERMISSIONS: string[] = [] // 所有已登录用户可访问
