export const LEARNING_CENTER_TITLE = '学习中心'
export const COURSE_RESOURCES_TITLE = '线上课程'
export const COMMUNITY_MANAGEMENT_TITLE = '社区中心'
export const COMMUNITY_RESOURCE_MANAGE_TITLE = '社区看板'
export const RESOURCE_BROWSE_TITLE = '社区助手'
export const MY_UPLOAD_TITLE = '社区管理'
