export const LEARNING_CENTER_TITLE = '知识中心'
export const COURSE_RESOURCES_TITLE = '线上课程管理'
export const COMMUNITY_CENTER_TITLE = '社区中心'
export const COMMUNITY_BOARD_TITLE = '社区看板'
export const COMMUNITY_ASSISTANT_TITLE = '社区助手'
export const COMMUNITY_MANAGEMENT_TITLE = '社区管理'
export const MY_UPLOAD_TITLE = '我的上传'
