export const DASHBOARD_PAGE_PERMISSIONS = ['GET_DASHBOARD']
export const COURSE_PAGE_PERMISSIONS = ['GET_COURSES', 'GET_COURSE_DETAIL']
export const EXAM_LIST_PAGE_PERMISSIONS = ['GET_EXAMS', 'SUBMIT_EXAM', 'GET_EXAM_RESULT']
export const EXAM_MANAGE_PAGE_PERMISSIONS = ['CREATE_EXAM', 'GET_EXAM_SCORES']
export const PAPER_PAGE_PERMISSIONS = ['CREATE_EXAM']
export const QUESTION_BANK_PAGE_PERMISSIONS = [
  'GET_QUESTIONS',
  'CREATE_QUESTION',
  'UPDATE_QUESTION',
  'DELETE_QUESTION',
  'BATCH_CREATE_QUESTIONS',
]
export const KNOWLEDGE_POINT_PAGE_PERMISSIONS = [
  'GET_KNOWLEDGE_POINTS',
  'CREATE_KNOWLEDGE_POINT',
  'UPDATE_KNOWLEDGE_POINT',
  'DELETE_KNOWLEDGE_POINT',
]
export const AI_QUESTION_PAGE_PERMISSIONS = [
  'GET_AI_QUESTION_TASKS',
  'CREATE_AI_QUESTION_TASK',
  'UPDATE_AI_QUESTION_TASK',
  'CONFIRM_AI_QUESTION_TASK',
]
export const AI_PAPER_ASSEMBLE_PAGE_PERMISSIONS = [
  'GET_AI_PAPER_ASSEMBLY_TASKS',
  'CREATE_AI_PAPER_ASSEMBLY_TASK',
  'UPDATE_AI_PAPER_ASSEMBLY_TASK',
  'CONFIRM_AI_PAPER_ASSEMBLY_TASK',
]
export const AI_PAPER_GENERATE_PAGE_PERMISSIONS = [
  'GET_AI_PAPER_GENERATION_TASKS',
  'CREATE_AI_PAPER_GENERATION_TASK',
  'UPDATE_AI_PAPER_GENERATION_TASK',
  'CONFIRM_AI_PAPER_GENERATION_TASK',
]
export const TRAINING_PAGE_PERMISSIONS = ['GET_TRAININGS', 'GET_TRAINING_DETAIL']
export const TRAINING_BASE_PAGE_PERMISSIONS = ['CREATE_TRAINING', 'UPDATE_TRAINING', 'MANAGE_TRAINING']
export const TRAINING_MANAGE_PAGE_PERMISSIONS = ['UPDATE_TRAINING', 'MANAGE_TRAINING']
export const TRAINING_SCHEDULE_PAGE_PERMISSIONS = ['GET_TRAINING_SCHEDULE']
export const REPORT_PAGE_PERMISSIONS = [
  'GET_REPORT_KPI',
  'GET_REPORT_TREND',
  'GET_POLICE_TYPE_DIST',
  'GET_CITY_RANKING',
]
export const MY_RESOURCE_PAGE_PERMISSIONS = ['CREATE_RESOURCE', 'UPDATE_RESOURCE', 'SUBMIT_RESOURCE_REVIEW']
export const TEACHING_RESOURCE_GENERATION_PAGE_PERMISSIONS = ['USE_TEACHING_RESOURCE_GENERATION']
export const RESOURCE_MANAGE_PAGE_PERMISSIONS = ['UPDATE_RESOURCE', 'VIEW_RESOURCE_ALL', 'MANAGE_RESOURCE_VISIBILITY']
export const RESOURCE_REVIEW_PAGE_PERMISSIONS = ['REVIEW_RESOURCE_STAGE1', 'REVIEW_RESOURCE_STAGE2']
export const RESOURCE_POLICY_PAGE_PERMISSIONS = ['MANAGE_REVIEW_POLICY']
export const USER_ARCHIVE_PAGE_PERMISSIONS = ['GET_USERS']
export const TALENT_PAGE_PERMISSIONS = ['GET_TALENTS', 'GET_TALENT_STATS']
export const CERTIFICATE_PAGE_PERMISSIONS = ['GET_CERTIFICATES', 'CREATE_CERTIFICATE']
export const USER_MANAGE_PAGE_PERMISSIONS = [
  'GET_USERS',
  'CREATE_USER',
  'UPDATE_USER',
  'DELETE_USER',
  'IMPORT_USERS',
  'EXPORT_USERS',
]
export const ROLE_MANAGE_PAGE_PERMISSIONS = [
  'GET_ROLES',
  'CREATE_ROLE',
  'UPDATE_ROLE',
  'DELETE_ROLE',
  'UPDATE_ROLE_PERMISSIONS',
  'IMPORT_ROLES',
  'EXPORT_ROLES',
]
export const DEPARTMENT_MANAGE_PAGE_PERMISSIONS = [
  'GET_DEPARTMENTS',
  'CREATE_DEPARTMENT',
  'UPDATE_DEPARTMENT',
  'DELETE_DEPARTMENT',
  'IMPORT_DEPARTMENTS',
  'EXPORT_DEPARTMENTS',
]
export const DICT_MANAGE_PAGE_PERMISSIONS = [
  'GET_POLICE_TYPES',
  'CREATE_POLICE_TYPE',
  'UPDATE_POLICE_TYPE',
  'DELETE_POLICE_TYPE',
]
export const ENROLL_MANAGE_PAGE_PERMISSIONS = [
  'GET_ENROLLMENTS',
  'APPROVE_ENROLLMENT',
  'REJECT_ENROLLMENT',
  'UPDATE_TRAINING',
  'MANAGE_TRAINING',
]
