"""add training_base fields

Revision ID: 764d58596f22
Revises: 5b9ab54afbd4
Create Date: 2026-04-07 14:12:59.136442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d58596f22'
down_revision: Union[str, None] = '5b9ab54afbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_bases', sa.Column('capacity', sa.Integer(), nullable=True, comment='最大容纳人数'))
    op.add_column('training_bases', sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'))
    op.add_column('training_bases', sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'))
    op.add_column('training_bases', sa.Column('area_size', sa.String(length=50), nullable=True, comment='占地面积'))
    op.add_column('training_bases', sa.Column('facilities', sa.String(length=500), nullable=True, comment='设施设备描述'))
    op.add_column('training_bases', sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/inactive'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_bases', 'status')
    op.drop_column('training_bases', 'facilities')
    op.drop_column('training_bases', 'area_size')
    op.drop_column('training_bases', 'contact_phone')
    op.drop_column('training_bases', 'contact_person')
    op.drop_column('training_bases', 'capacity')
    # ### end Alembic commands ###
