"""add course_id to training_courses

Revision ID: 9e5cca41ad53
Revises: d5e6f7a8b9c0
Create Date: 2026-04-02 16:36:39.845528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e5cca41ad53'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notice_reads', 'notice_id',
               existing_type=sa.INTEGER(),
               comment='通知ID',
               existing_nullable=False)
    op.alter_column('notice_reads', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('notice_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='已读时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notice_reads_id'), 'notice_reads', ['id'], unique=False)
    op.alter_column('notices', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='类型: system/training/reminder',
               existing_comment='类型: system/training',
               existing_nullable=True)
    op.alter_column('notices', 'reminder_type',
               existing_type=sa.VARCHAR(length=50),
               comment='提醒子类型: exam_reminder/review_approved/review_rejected/enrollment_approved 等',
               existing_comment='提醒子类型',
               existing_nullable=True)
    op.add_column('training_courses', sa.Column('course_id', sa.Integer(), nullable=True, comment='关联课程资源ID(为空则是自定义课程)'))
    op.create_index(op.f('ix_training_courses_course_id'), 'training_courses', ['course_id'], unique=False)
    op.create_foreign_key(None, 'training_courses', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_courses', type_='foreignkey')
    op.drop_index(op.f('ix_training_courses_course_id'), table_name='training_courses')
    op.drop_column('training_courses', 'course_id')
    op.alter_column('notices', 'reminder_type',
               existing_type=sa.VARCHAR(length=50),
               comment='提醒子类型',
               existing_comment='提醒子类型: exam_reminder/review_approved/review_rejected/enrollment_approved 等',
               existing_nullable=True)
    op.alter_column('notices', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='类型: system/training',
               existing_comment='类型: system/training/reminder',
               existing_nullable=True)
    op.drop_index(op.f('ix_notice_reads_id'), table_name='notice_reads')
    op.alter_column('notice_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='已读时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notice_reads', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('notice_reads', 'notice_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='通知ID',
               existing_nullable=False)
    # ### end Alembic commands ###
