"""add instructor_tags and dict_instructor_specialties

Revision ID: 6128362bb82b
Revises: abf0a750a75e
Create Date: 2026-04-08 17:23:41.310443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6128362bb82b'
down_revision: Union[str, None] = 'abf0a750a75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_instructor_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='专长方向名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dict_instructor_specialties_id'), 'dict_instructor_specialties', ['id'], unique=False)
    op.create_table('instructor_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='教官用户ID'),
    sa.Column('admin_level', sa.String(length=20), nullable=False, comment='行政级别: 厅级/市级/县级'),
    sa.Column('professional_level', sa.String(length=20), nullable=False, comment='专业等级: 初级/中级/高级'),
    sa.Column('specialty_id', sa.Integer(), nullable=False, comment='专长方向ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['specialty_id'], ['dict_instructor_specialties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'admin_level', 'professional_level', 'specialty_id', name='uq_instructor_tag')
    )
    op.create_index(op.f('ix_instructor_tags_id'), 'instructor_tags', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_tags_user_id'), 'instructor_tags', ['user_id'], unique=False)
    op.drop_column('users', 'instructor_qualification')
    op.drop_column('users', 'instructor_admin_level')
    op.drop_column('users', 'instructor_level')
    op.drop_column('users', 'instructor_specialties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instructor_specialties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='教官专长数组'))
    op.add_column('users', sa.Column('instructor_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='教官专业等级: 初级/中级/高级'))
    op.add_column('users', sa.Column('instructor_admin_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='教官行政级别: 厅级/市级/县级'))
    op.add_column('users', sa.Column('instructor_qualification', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='教官资质数组'))
    op.drop_index(op.f('ix_instructor_tags_user_id'), table_name='instructor_tags')
    op.drop_index(op.f('ix_instructor_tags_id'), table_name='instructor_tags')
    op.drop_table('instructor_tags')
    op.drop_index(op.f('ix_dict_instructor_specialties_id'), table_name='dict_instructor_specialties')
    op.drop_table('dict_instructor_specialties')
    # ### end Alembic commands ###
