"""add_training_activities_table

Revision ID: 819162486835
Revises: a1b2c3d4e5f7
Create Date: 2026-04-01 17:08:01.901902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819162486835'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='冗余存储用户名'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='动态类型: checkin/checkout/notice/enroll/session_checkin_start/session_checkin_end/session_checkout_start/session_checkout_end'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='动态内容描述'),
    sa.Column('extra_json', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_activities_created_at'), 'training_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_activities_id'), 'training_activities', ['id'], unique=False)
    op.create_index(op.f('ix_training_activities_training_id'), 'training_activities', ['training_id'], unique=False)
    op.alter_column('knowledge_points', 'course_id',
               existing_type=sa.INTEGER(),
               comment='课程ID',
               existing_nullable=True)
    op.create_foreign_key(None, 'knowledge_points', 'courses', ['course_id'], ['id'])
    op.alter_column('media_files', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='媒体时长(秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('resource_behavior_events', 'event_type',
               existing_type=sa.VARCHAR(length=30),
               comment='事件类型: impression/click/play/complete/like/unlike/share/favorite',
               existing_comment='事件类型: impression/click/play/complete/like/favorite',
               existing_nullable=False)
    op.alter_column('resources', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='转发次数',
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='评论次数',
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='评论次数',
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='转发次数',
               existing_server_default=sa.text('0'))
    op.alter_column('resource_behavior_events', 'event_type',
               existing_type=sa.VARCHAR(length=30),
               comment='事件类型: impression/click/play/complete/like/favorite',
               existing_comment='事件类型: impression/click/play/complete/like/unlike/share/favorite',
               existing_nullable=False)
    op.alter_column('media_files', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='媒体时长(秒)',
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'knowledge_points', type_='foreignkey')
    op.alter_column('knowledge_points', 'course_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='课程ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_training_activities_training_id'), table_name='training_activities')
    op.drop_index(op.f('ix_training_activities_id'), table_name='training_activities')
    op.drop_index(op.f('ix_training_activities_created_at'), table_name='training_activities')
    op.drop_table('training_activities')
    # ### end Alembic commands ###
