"""course learning status and tags

Revision ID: 8738fe0d816a
Revises: b5c6d7e8f9a0
Create Date: 2026-03-16 16:02:46.211840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8738fe0d816a'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admission_exams', 'scope',
               existing_type=sa.VARCHAR(length=200),
               comment='适用范围摘要',
               existing_comment='适用范围',
               existing_nullable=True)
    op.alter_column('admission_exams', 'scope_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_comment='适用范围类型: all/user/department/role',
               existing_server_default=sa.text("'all'::character varying"))
    op.alter_column('ai_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始处理时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='处理完成时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='确认完成时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)

    op.alter_column('checkin_records', 'session_key',
               existing_type=sa.VARCHAR(length=100),
               comment='课次标识',
               existing_comment='签到场次标识',
               existing_nullable=False)
    op.alter_column('checkin_records', 'checkin_method',
               existing_type=sa.VARCHAR(length=20),
               comment='签到方式: qr/manual',
               existing_comment='签到方式',
               existing_nullable=True)
    op.alter_column('checkin_records', 'checkout_time',
               existing_type=sa.VARCHAR(length=10),
               comment='签退时间 HH:MM',
               existing_comment='签退时间',
               existing_nullable=True)
    op.alter_column('checkin_records', 'checkout_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='签退状态: pending/completed',
               existing_comment='签退状态',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('checkin_records', 'checkout_method',
               existing_type=sa.VARCHAR(length=20),
               comment='签退方式: qr/manual',
               existing_comment='签退方式',
               existing_nullable=True)
    op.alter_column('checkin_records', 'evaluation_submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='评课提交时间',
               existing_comment='评课时间',
               existing_nullable=True)
    op.alter_column('checkin_records', 'absence_reason',
               existing_type=sa.TEXT(),
               comment='缺勤原因/留痕',
               existing_comment='缺勤原因',
               existing_nullable=True)
    op.add_column('course_progress', sa.Column('playback_seconds', sa.Integer(), nullable=True, comment='最近播放位置(秒)'))
    op.add_column('courses', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_foreign_key(None, 'courses', 'users', ['created_by'], ['id'])
    op.drop_column('courses', 'tags')
    op.alter_column('enrollments', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='报名联系电话',
               existing_comment='联系电话',
               existing_nullable=True)
    op.alter_column('enrollments', 'need_accommodation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否需要住宿',
               existing_server_default=sa.text('false'))
    op.alter_column('enrollments', 'profile_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='报名时档案快照',
               existing_comment='报名档案快照',
               existing_nullable=True)
    op.alter_column('exam_paper_questions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='题目排序',
               existing_server_default=sa.text('0'))
    op.alter_column('exam_papers', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='考试时长(分钟)',
               existing_server_default=sa.text('60'))
    op.alter_column('exam_papers', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='总分',
               existing_server_default=sa.text('100'))
    op.alter_column('exam_papers', 'passing_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='及格分',
               existing_server_default=sa.text('60'))
    op.alter_column('exam_papers', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='试卷类型: formal/quiz',
               existing_comment='试卷类型',
               existing_server_default=sa.text("'formal'::character varying"))
    op.alter_column('exam_papers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='试卷状态: draft/published/archived',
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('exam_papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exam_papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)

    op.alter_column('exam_questions', 'question_id',
               existing_type=sa.INTEGER(),
               comment='来源题目ID',
               existing_nullable=False)
    op.alter_column('exam_questions', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='分值快照')
    op.alter_column('exam_records', 'exam_id',
               existing_type=sa.INTEGER(),
               comment='考试场次ID',
               existing_comment='考试ID',
               existing_nullable=False)
    op.alter_column('exam_records', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='试卷ID')
    op.alter_column('exam_records', 'attempt_no',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='第几次作答',
               existing_server_default=sa.text('1'))
    op.alter_column('exam_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='状态: submitted/absent/exempt',
               existing_comment='作答状态',
               existing_server_default=sa.text("'submitted'::character varying"))
    op.execute('DROP INDEX IF EXISTS ix_exam_records_paper_id')
    op.alter_column('exams', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='试卷ID')
    op.alter_column('exams', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='场次标题',
               existing_comment='考试标题',
               existing_nullable=False)
    op.alter_column('exams', 'description',
               existing_type=sa.TEXT(),
               comment='场次描述',
               existing_comment='考试描述',
               existing_nullable=True)
    op.alter_column('exams', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='展示类型: formal/quiz',
               existing_comment='类型: formal/quiz',
               existing_nullable=True)
    op.alter_column('exams', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='用途: class_assessment/final_assessment/quiz/makeup',
               existing_comment='用途',
               existing_server_default=sa.text("'class_assessment'::character varying"))
    op.alter_column('exams', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='关联培训班ID')
    op.alter_column('exams', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='最大作答次数',
               existing_server_default=sa.text('1'))
    op.alter_column('exams', 'allow_makeup',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否允许补考',
               existing_server_default=sa.text('false'))
    op.execute('DROP INDEX IF EXISTS ix_exams_paper_id')
    op.execute('DROP INDEX IF EXISTS ix_exams_training_id')
    op.alter_column('questions', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='答案 string 或 string[]',
               existing_comment='答案 string或string[]',
               existing_nullable=False)
    op.alter_column('roles', 'data_scopes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='数据范围列表',
               existing_nullable=True)
    op.alter_column('schedule_items', 'day',
               existing_type=sa.INTEGER(),
               comment='星期1-7',
               existing_comment='星期1-5',
               existing_nullable=True)
    op.alter_column('training_bases', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('training_courses', 'instructor',
               existing_type=sa.VARCHAR(length=100),
               comment='主讲教官名称',
               existing_comment='授课教官',
               existing_nullable=True)
    op.alter_column('training_courses', 'schedules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='排课清单，包含课次状态与签到签退生命周期',
               existing_comment='排课清单',
               existing_nullable=True)
    op.alter_column('training_histories', 'training_id',
               existing_type=sa.INTEGER(),
               comment='培训班ID',
               existing_nullable=False)
    op.alter_column('training_histories', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('training_histories', 'training_name',
               existing_type=sa.VARCHAR(length=200),
               comment='培训名称快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'training_type',
               existing_type=sa.VARCHAR(length=50),
               comment='培训类型快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='培训状态快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'start_date',
               existing_type=sa.DATE(),
               comment='开始日期',
               existing_nullable=True)
    op.alter_column('training_histories', 'end_date',
               existing_type=sa.DATE(),
               comment='结束日期',
               existing_nullable=True)
    op.alter_column('training_histories', 'attendance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='出勤率',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'completed_sessions',
               existing_type=sa.INTEGER(),
               comment='完成课次',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'total_sessions',
               existing_type=sa.INTEGER(),
               comment='总课次',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'evaluation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='评课均分',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'passed_exam_count',
               existing_type=sa.INTEGER(),
               comment='通过考试场次数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='归档时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('training_histories', 'summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='扩展摘要',
               existing_nullable=True)

    op.alter_column('trainings', 'publish_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='发布状态: draft/published',
               existing_comment='发布状态',
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('trainings', 'instructor_id',
               existing_type=sa.INTEGER(),
               comment='班主任ID',
               existing_comment='负责教官ID',
               existing_nullable=True)
    op.alter_column('trainings', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('trainings', 'admission_exam_id',
               existing_type=sa.INTEGER(),
               comment='准入考试ID',
               existing_comment='准入考试场次ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'admission_exam_id',
               existing_type=sa.INTEGER(),
               comment='准入考试场次ID',
               existing_comment='准入考试ID',
               existing_nullable=True)
    op.alter_column('trainings', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('trainings', 'instructor_id',
               existing_type=sa.INTEGER(),
               comment='负责教官ID',
               existing_comment='班主任ID',
               existing_nullable=True)
    op.alter_column('trainings', 'publish_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='发布状态',
               existing_comment='发布状态: draft/published',
               existing_server_default=sa.text("'draft'::character varying"))

    op.alter_column('training_histories', 'summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展摘要',
               existing_nullable=True)
    op.alter_column('training_histories', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='归档时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('training_histories', 'passed_exam_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='通过考试场次数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'evaluation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='评课均分',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'total_sessions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总课次',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'completed_sessions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='完成课次',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'attendance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='出勤率',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('training_histories', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='结束日期',
               existing_nullable=True)
    op.alter_column('training_histories', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='开始日期',
               existing_nullable=True)
    op.alter_column('training_histories', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='培训状态快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'training_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='培训类型快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'training_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='培训名称快照',
               existing_nullable=False)
    op.alter_column('training_histories', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('training_histories', 'training_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='培训班ID',
               existing_nullable=False)
    op.alter_column('training_courses', 'schedules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='排课清单',
               existing_comment='排课清单，包含课次状态与签到签退生命周期',
               existing_nullable=True)
    op.alter_column('training_courses', 'instructor',
               existing_type=sa.VARCHAR(length=100),
               comment='授课教官',
               existing_comment='主讲教官名称',
               existing_nullable=True)
    op.alter_column('training_bases', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('schedule_items', 'day',
               existing_type=sa.INTEGER(),
               comment='星期1-5',
               existing_comment='星期1-7',
               existing_nullable=True)
    op.alter_column('roles', 'data_scopes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='数据范围列表',
               existing_nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='答案 string或string[]',
               existing_comment='答案 string 或 string[]',
               existing_nullable=False)
    op.execute('CREATE INDEX IF NOT EXISTS ix_exams_training_id ON exams (training_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_exams_paper_id ON exams (paper_id)')
    op.alter_column('exams', 'allow_makeup',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否允许补考',
               existing_server_default=sa.text('false'))
    op.alter_column('exams', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='最大作答次数',
               existing_server_default=sa.text('1'))
    op.alter_column('exams', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='关联培训班ID')
    op.alter_column('exams', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='用途',
               existing_comment='用途: class_assessment/final_assessment/quiz/makeup',
               existing_server_default=sa.text("'class_assessment'::character varying"))
    op.alter_column('exams', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='类型: formal/quiz',
               existing_comment='展示类型: formal/quiz',
               existing_nullable=True)
    op.alter_column('exams', 'description',
               existing_type=sa.TEXT(),
               comment='考试描述',
               existing_comment='场次描述',
               existing_nullable=True)
    op.alter_column('exams', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='考试标题',
               existing_comment='场次标题',
               existing_nullable=False)
    op.alter_column('exams', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='试卷ID')
    op.execute('CREATE INDEX IF NOT EXISTS ix_exam_records_paper_id ON exam_records (paper_id)')
    op.alter_column('exam_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='作答状态',
               existing_comment='状态: submitted/absent/exempt',
               existing_server_default=sa.text("'submitted'::character varying"))
    op.alter_column('exam_records', 'attempt_no',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='第几次作答',
               existing_server_default=sa.text('1'))
    op.alter_column('exam_records', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='试卷ID')
    op.alter_column('exam_records', 'exam_id',
               existing_type=sa.INTEGER(),
               comment='考试ID',
               existing_comment='考试场次ID',
               existing_nullable=False)
    op.alter_column('exam_questions', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='分值快照')
    op.alter_column('exam_questions', 'question_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='来源题目ID',
               existing_nullable=False)

    op.alter_column('exam_papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('exam_papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exam_papers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='试卷状态: draft/published/archived',
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('exam_papers', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='试卷类型',
               existing_comment='试卷类型: formal/quiz',
               existing_server_default=sa.text("'formal'::character varying"))
    op.alter_column('exam_papers', 'passing_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='及格分',
               existing_server_default=sa.text('60'))
    op.alter_column('exam_papers', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='总分',
               existing_server_default=sa.text('100'))
    op.alter_column('exam_papers', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='考试时长(分钟)',
               existing_server_default=sa.text('60'))
    op.alter_column('exam_paper_questions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='题目排序',
               existing_server_default=sa.text('0'))
    op.alter_column('enrollments', 'profile_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='报名档案快照',
               existing_comment='报名时档案快照',
               existing_nullable=True)
    op.alter_column('enrollments', 'need_accommodation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否需要住宿',
               existing_server_default=sa.text('false'))
    op.alter_column('enrollments', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系电话',
               existing_comment='报名联系电话',
               existing_nullable=True)
    op.add_column('courses', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='标签数组'))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_column('courses', 'created_by')
    op.drop_column('course_progress', 'playback_seconds')
    op.alter_column('checkin_records', 'absence_reason',
               existing_type=sa.TEXT(),
               comment='缺勤原因',
               existing_comment='缺勤原因/留痕',
               existing_nullable=True)
    op.alter_column('checkin_records', 'evaluation_submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='评课时间',
               existing_comment='评课提交时间',
               existing_nullable=True)
    op.alter_column('checkin_records', 'checkout_method',
               existing_type=sa.VARCHAR(length=20),
               comment='签退方式',
               existing_comment='签退方式: qr/manual',
               existing_nullable=True)
    op.alter_column('checkin_records', 'checkout_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='签退状态',
               existing_comment='签退状态: pending/completed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('checkin_records', 'checkout_time',
               existing_type=sa.VARCHAR(length=10),
               comment='签退时间',
               existing_comment='签退时间 HH:MM',
               existing_nullable=True)
    op.alter_column('checkin_records', 'checkin_method',
               existing_type=sa.VARCHAR(length=20),
               comment='签到方式',
               existing_comment='签到方式: qr/manual',
               existing_nullable=True)
    op.alter_column('checkin_records', 'session_key',
               existing_type=sa.VARCHAR(length=100),
               comment='签到场次标识',
               existing_comment='课次标识',
               existing_nullable=False)

    op.alter_column('ai_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='确认完成时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='处理完成时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始处理时间',
               existing_nullable=True)
    op.alter_column('ai_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admission_exams', 'scope_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_comment='适用范围类型: all/user/department/role',
               existing_server_default=sa.text("'all'::character varying"))
    op.alter_column('admission_exams', 'scope',
               existing_type=sa.VARCHAR(length=200),
               comment='适用范围',
               existing_comment='适用范围摘要',
               existing_nullable=True)
    # ### end Alembic commands ###
