"""add_training_type_table_and_training_type_id

Revision ID: a3d174a9a2c6
Revises: 1a2b3c4d5e6f
Create Date: 2026-04-01 09:46:10.054357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a3d174a9a2c6'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())

    # 检查并添加 exam_papers.folder_id 注释（幂等）
    exam_papers_columns = [c['name'] for c in inspector.get_columns('exam_papers')]
    if 'folder_id' in exam_papers_columns:
        op.alter_column('exam_papers', 'folder_id',
                   existing_type=sa.INTEGER(),
                   comment='所属文件夹ID',
                   existing_nullable=True)

    # 检查并添加 questions.folder_id 注释（幂等）
    questions_columns = [c['name'] for c in inspector.get_columns('questions')]
    if 'folder_id' in questions_columns:
        op.alter_column('questions', 'folder_id',
                   existing_type=sa.INTEGER(),
                   comment='所属文件夹ID',
                   existing_nullable=True)

    # 检查 training_type_id 列是否已存在（幂等）
    trainings_columns = [c['name'] for c in inspector.get_columns('trainings')]
    if 'training_type_id' not in trainings_columns:
        op.add_column('trainings', sa.Column('training_type_id', sa.Integer(), nullable=True, comment='培训班类型ID'))

    # 检查外键是否已存在（幂等）
    constraints = inspector.get_foreign_keys('trainings')
    fk_exists = any(
        c.get('referred_table') == 'training_types' and 'training_type_id' in (c.get('referred_columns') or [])
        for c in constraints
    )
    if not fk_exists:
        op.create_foreign_key(None, 'trainings', 'training_types', ['training_type_id'], ['id'])
    # ### end Alembic commands ###

    # 回填：将已有 trainings.type 字符串映射到 training_types.id
    op.execute(
        "UPDATE trainings SET training_type_id = ("
        "  SELECT id FROM training_types WHERE training_types.code = trainings.type"
        ") WHERE training_type_id IS NULL AND type IS NOT NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())

    # 检查并删除外键（幂等）
    constraints = inspector.get_foreign_keys('trainings')
    fk_exists = any(
        c.get('referred_table') == 'training_types' and 'training_type_id' in (c.get('referred_columns') or [])
        for c in constraints
    )
    if fk_exists:
        op.drop_constraint(None, 'trainings', type_='foreignkey')

    # 检查并删除列（幂等）
    trainings_columns = [c['name'] for c in inspector.get_columns('trainings')]
    if 'training_type_id' in trainings_columns:
        op.drop_column('trainings', 'training_type_id')

    # 恢复 questions.folder_id 注释（幂等）
    questions_columns = [c['name'] for c in inspector.get_columns('questions')]
    if 'folder_id' in questions_columns:
        op.alter_column('questions', 'folder_id',
                   existing_type=sa.INTEGER(),
                   comment=None,
                   existing_comment='所属文件夹ID',
                   existing_nullable=True)

    # 恢复 exam_papers.folder_id 注释（幂等）
    exam_papers_columns = [c['name'] for c in inspector.get_columns('exam_papers')]
    if 'folder_id' in exam_papers_columns:
        op.alter_column('exam_papers', 'folder_id',
                   existing_type=sa.INTEGER(),
                   comment=None,
                   existing_comment='所属文件夹ID',
                   existing_nullable=True)
    # ### end Alembic commands ###
