"""add ai review fields to review policy stages

Revision ID: 3713f097bab0
Revises: 89c1f9829384
Create Date: 2026-04-09 15:25:53.962701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3713f097bab0'
down_revision: Union[str, None] = '89c1f9829384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_policy_stages', sa.Column('fallback_reviewer_type', sa.String(length=30), nullable=True, comment='AI降级审核人类型: role/department/user'))
    op.add_column('review_policy_stages', sa.Column('fallback_reviewer_ref_id', sa.Integer(), nullable=True, comment='AI降级审核对象ID'))
    op.add_column('review_policy_stages', sa.Column('ai_reject_mode', sa.String(length=20), nullable=True, comment='AI拒绝策略: direct/fallback'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_policy_stages', 'ai_reject_mode')
    op.drop_column('review_policy_stages', 'fallback_reviewer_ref_id')
    op.drop_column('review_policy_stages', 'fallback_reviewer_type')
    # ### end Alembic commands ###
