"""add knowledge_base and scenario models

Revision ID: 021f05c8dd6a
Revises: cf51b97aadea
Create Date: 2026-04-09 09:00:27.980327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '021f05c8dd6a'
down_revision: Union[str, None] = 'cf51b97aadea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见范围: all/instructor/admin'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='文档数量'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='引用次数'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_created_by'), 'knowledge_bases', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_table('knowledge_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True, comment='关联知识库 ID'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='对话模式: qa/generate/case'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='对话消息列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chat_sessions_id'), 'knowledge_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_chat_sessions_knowledge_base_id'), 'knowledge_chat_sessions', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chat_sessions_user_id'), 'knowledge_chat_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False, comment='所属知识库 ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='文档标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档全文内容'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源类型: manual/import/ai_generated'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_created_by'), 'knowledge_documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_table('scenario_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='场景名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景描述'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='场景分类: law_enforcement/record_taking/law_application'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度等级 1-5'),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False, comment='预计时长(分钟)'),
    sa.Column('background', sa.Text(), nullable=False, comment='场景背景描述'),
    sa.Column('npc_role', sa.Text(), nullable=False, comment='AI 扮演角色描述'),
    sa.Column('npc_name', sa.String(length=50), nullable=True, comment='AI 角色名称'),
    sa.Column('npc_opening', sa.Text(), nullable=True, comment='AI 开场白'),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True, comment='关联知识库 ID'),
    sa.Column('checkpoints', sa.JSON(), nullable=False, comment='考察要点 [{label, score}]'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/published/archived'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_templates_category'), 'scenario_templates', ['category'], unique=False)
    op.create_index(op.f('ix_scenario_templates_created_by'), 'scenario_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_scenario_templates_id'), 'scenario_templates', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_templates_status'), 'scenario_templates', ['status'], unique=False)
    op.create_table('scenario_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_template_id', sa.Integer(), nullable=False, comment='场景模板 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='对话消息列表 [{role, content, npc_name?}]'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: in_progress/completed'),
    sa.Column('score', sa.Integer(), nullable=True, comment='综合评分 0-100'),
    sa.Column('checkpoint_results', sa.JSON(), nullable=True, comment='考察要点结果 [{label, passed}]'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='AI 评价反馈'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='用时(分钟)'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['scenario_template_id'], ['scenario_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_sessions_id'), 'scenario_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_sessions_scenario_template_id'), 'scenario_sessions', ['scenario_template_id'], unique=False)
    op.create_index(op.f('ix_scenario_sessions_user_id'), 'scenario_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_sessions_user_id'), table_name='scenario_sessions')
    op.drop_index(op.f('ix_scenario_sessions_scenario_template_id'), table_name='scenario_sessions')
    op.drop_index(op.f('ix_scenario_sessions_id'), table_name='scenario_sessions')
    op.drop_table('scenario_sessions')
    op.drop_index(op.f('ix_scenario_templates_status'), table_name='scenario_templates')
    op.drop_index(op.f('ix_scenario_templates_id'), table_name='scenario_templates')
    op.drop_index(op.f('ix_scenario_templates_created_by'), table_name='scenario_templates')
    op.drop_index(op.f('ix_scenario_templates_category'), table_name='scenario_templates')
    op.drop_table('scenario_templates')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_created_by'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_chat_sessions_user_id'), table_name='knowledge_chat_sessions')
    op.drop_index(op.f('ix_knowledge_chat_sessions_knowledge_base_id'), table_name='knowledge_chat_sessions')
    op.drop_index(op.f('ix_knowledge_chat_sessions_id'), table_name='knowledge_chat_sessions')
    op.drop_table('knowledge_chat_sessions')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_created_by'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
