"""add instructor profile fields and tables

Revision ID: 89c1f9829384
Revises: f0e1d2c3b4a5
Create Date: 2026-04-09 14:53:51.720162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c1f9829384'
down_revision: Union[str, None] = 'f0e1d2c3b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_teaching_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='教学方向名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dict_teaching_directions_id'), 'dict_teaching_directions', ['id'], unique=False)
    op.create_table('instructor_teaching_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='教官用户ID'),
    sa.Column('direction_id', sa.Integer(), nullable=False, comment='教学方向ID'),
    sa.ForeignKeyConstraint(['direction_id'], ['dict_teaching_directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'direction_id', name='uq_instructor_teaching_direction')
    )
    op.create_index(op.f('ix_instructor_teaching_directions_direction_id'), 'instructor_teaching_directions', ['direction_id'], unique=False)
    op.create_index(op.f('ix_instructor_teaching_directions_id'), 'instructor_teaching_directions', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_teaching_directions_user_id'), 'instructor_teaching_directions', ['user_id'], unique=False)
    op.create_table('instructor_teaching_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='教官用户ID'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('target_audience', sa.String(length=200), nullable=True, comment='授课对象'),
    sa.Column('content', sa.Text(), nullable=True, comment='授课内容'),
    sa.Column('evaluation', sa.Text(), nullable=True, comment='评课情况'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_teaching_experiences_id'), 'instructor_teaching_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_teaching_experiences_user_id'), 'instructor_teaching_experiences', ['user_id'], unique=False)
    op.alter_column('knowledge_chat_sessions', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='历史关联知识库 ID',
               existing_comment='关联知识库 ID',
               existing_nullable=True)
    op.alter_column('knowledge_chat_sessions', 'knowledge_item_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关联知识点 ID 列表',
               existing_nullable=False)
    op.alter_column('knowledge_chat_sessions', 'mode',
               existing_type=sa.VARCHAR(length=20),
               comment='对话模式: qa/case',
               existing_comment='对话模式: qa/generate/case',
               existing_nullable=False)
    op.alter_column('scenario_templates', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='历史关联知识库 ID',
               existing_comment='关联知识库 ID',
               existing_nullable=True)
    op.alter_column('scenario_templates', 'knowledge_item_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关联知识点 ID 列表',
               existing_nullable=False)
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'))
    op.add_column('users', sa.Column('native_place', sa.String(length=100), nullable=True, comment='籍贯'))
    op.add_column('users', sa.Column('ethnicity', sa.String(length=50), nullable=True, comment='民族'))
    op.add_column('users', sa.Column('education', sa.String(length=50), nullable=True, comment='学历'))
    op.add_column('users', sa.Column('degree', sa.String(length=50), nullable=True, comment='学位'))
    op.add_column('users', sa.Column('instructor_job_type', sa.String(length=20), nullable=True, comment='岗位类型: 专职/兼职'))
    op.add_column('users', sa.Column('instructor_category', sa.String(length=20), nullable=True, comment='师资类型: 业务/技能'))
    op.add_column('users', sa.Column('instructor_level', sa.String(length=20), nullable=True, comment='教官等级: 高级/中级/初级'))
    op.add_column('users', sa.Column('instructor_hire_start', sa.Date(), nullable=True, comment='聘任开始日期'))
    op.add_column('users', sa.Column('instructor_hire_end', sa.Date(), nullable=True, comment='聘任结束日期'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instructor_hire_end')
    op.drop_column('users', 'instructor_hire_start')
    op.drop_column('users', 'instructor_level')
    op.drop_column('users', 'instructor_category')
    op.drop_column('users', 'instructor_job_type')
    op.drop_column('users', 'degree')
    op.drop_column('users', 'education')
    op.drop_column('users', 'ethnicity')
    op.drop_column('users', 'native_place')
    op.drop_column('users', 'birth_date')
    op.alter_column('scenario_templates', 'knowledge_item_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关联知识点 ID 列表',
               existing_nullable=False)
    op.alter_column('scenario_templates', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='关联知识库 ID',
               existing_comment='历史关联知识库 ID',
               existing_nullable=True)
    op.alter_column('knowledge_chat_sessions', 'mode',
               existing_type=sa.VARCHAR(length=20),
               comment='对话模式: qa/generate/case',
               existing_comment='对话模式: qa/case',
               existing_nullable=False)
    op.alter_column('knowledge_chat_sessions', 'knowledge_item_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关联知识点 ID 列表',
               existing_nullable=False)
    op.alter_column('knowledge_chat_sessions', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='关联知识库 ID',
               existing_comment='历史关联知识库 ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_instructor_teaching_experiences_user_id'), table_name='instructor_teaching_experiences')
    op.drop_index(op.f('ix_instructor_teaching_experiences_id'), table_name='instructor_teaching_experiences')
    op.drop_table('instructor_teaching_experiences')
    op.drop_index(op.f('ix_instructor_teaching_directions_user_id'), table_name='instructor_teaching_directions')
    op.drop_index(op.f('ix_instructor_teaching_directions_id'), table_name='instructor_teaching_directions')
    op.drop_index(op.f('ix_instructor_teaching_directions_direction_id'), table_name='instructor_teaching_directions')
    op.drop_table('instructor_teaching_directions')
    op.drop_index(op.f('ix_dict_teaching_directions_id'), table_name='dict_teaching_directions')
    op.drop_table('dict_teaching_directions')
    # ### end Alembic commands ###
