"""add training course location

Revision ID: 2bad6e1b18de
Revises: 48124f7b14b6
Create Date: 2026-03-16 17:52:08.638718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bad6e1b18de'
down_revision: Union[str, None] = '48124f7b14b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_courses', sa.Column('location', sa.String(length=200), nullable=True, comment='课程地点'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_courses', 'location')
    # ### end Alembic commands ###
