"""add instructor_admin_level and teaching_records

Revision ID: abf0a750a75e
Revises: ce901f6434c1
Create Date: 2026-04-08 16:51:22.625649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf0a750a75e'
down_revision: Union[str, None] = 'ce901f6434c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_teaching_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='教官用户ID'),
    sa.Column('training_id', sa.Integer(), nullable=False, comment='培训班ID'),
    sa.Column('training_course_id', sa.Integer(), nullable=True, comment='培训课程ID'),
    sa.Column('training_name', sa.String(length=200), nullable=False, comment='培训班名称快照'),
    sa.Column('course_name', sa.String(length=200), nullable=True, comment='课程名称快照'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='授课地点'),
    sa.Column('hours', sa.Float(), nullable=True, comment='授课课时'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色: primary/assistant'),
    sa.Column('student_count', sa.Integer(), nullable=True, comment='学员人数'),
    sa.Column('evaluation_avg', sa.Float(), nullable=True, comment='教学评价均分'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='培训开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='培训结束日期'),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='归档时间'),
    sa.ForeignKeyConstraint(['training_course_id'], ['training_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'training_id', 'training_course_id', name='uq_instructor_teaching_record')
    )
    op.create_index(op.f('ix_instructor_teaching_records_id'), 'instructor_teaching_records', ['id'], unique=False)
    op.create_index('ix_instructor_teaching_training', 'instructor_teaching_records', ['training_id'], unique=False)
    op.create_index('ix_instructor_teaching_user', 'instructor_teaching_records', ['user_id'], unique=False)
    op.add_column('users', sa.Column('instructor_admin_level', sa.String(length=20), nullable=True, comment='教官行政级别: 厅级/市级/县级'))
    op.alter_column('users', 'instructor_level',
               existing_type=sa.VARCHAR(length=20),
               comment='教官专业等级: 初级/中级/高级',
               existing_comment='教官等级',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'instructor_level',
               existing_type=sa.VARCHAR(length=20),
               comment='教官等级',
               existing_comment='教官专业等级: 初级/中级/高级',
               existing_nullable=True)
    op.drop_column('users', 'instructor_admin_level')
    op.drop_index('ix_instructor_teaching_user', table_name='instructor_teaching_records')
    op.drop_index('ix_instructor_teaching_training', table_name='instructor_teaching_records')
    op.drop_index(op.f('ix_instructor_teaching_records_id'), table_name='instructor_teaching_records')
    op.drop_table('instructor_teaching_records')
    # ### end Alembic commands ###
