"""add_course_qa

Revision ID: f8edba8d885b
Revises: 9b8c7d6e5f4a
Create Date: 2026-03-08 23:57:51.217503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8edba8d885b'
down_revision: Union[str, None] = '9b8c7d6e5f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='问题内容'),
    sa.Column('answer', sa.Text(), nullable=True, comment='回答内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='提问时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程答疑表'
    )
    op.create_index(op.f('ix_course_qa_id'), 'course_qa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_qa_id'), table_name='course_qa')
    op.drop_table('course_qa')
    # ### end Alembic commands ###
