"""add course notes table

Revision ID: fcaa5aebe6f6
Revises: 36667d124fcd
Create Date: 2026-03-07 17:12:34.974386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaa5aebe6f6'
down_revision: Union[str, None] = '36667d124fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='笔记内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_course_notes_user_course'),
    comment='课程笔记表'
    )
    op.create_index(op.f('ix_course_notes_id'), 'course_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_notes_id'), table_name='course_notes')
    op.drop_table('course_notes')
    # ### end Alembic commands ###
