"""add notices table

Revision ID: ef0e16b5cafc
Revises: 77250b8f89d2
Create Date: 2026-03-07 22:23:30.293999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0e16b5cafc'
down_revision: Union[str, None] = '77250b8f89d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='类型: system/training'),
    sa.Column('training_id', sa.Integer(), nullable=True, comment='培训班ID(培训班公告)'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='发布人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
