"""replace unit and police_type fields with police_types and user_police_types tables

Revision ID: fb59ba77bec3
Revises: e769113227d3
Create Date: 2026-03-06 16:47:20.576734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb59ba77bec3'
down_revision: Union[str, None] = 'e769113227d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unit')
    op.drop_column('users', 'police_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('police_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='警种'))
    op.add_column('users', sa.Column('unit', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='所属单位'))
    # ### end Alembic commands ###
