"""training bugfix fields

Revision ID: 77250b8f89d2
Revises: fcaa5aebe6f6
Create Date: 2026-03-07 18:39:07.641535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77250b8f89d2'
down_revision: Union[str, None] = 'fcaa5aebe6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
