"""add_training_type_table_and_training_type_id

Revision ID: a3d174a9a2c6
Revises: 1a2b3c4d5e6f
Create Date: 2026-04-01 09:46:10.054357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d174a9a2c6'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_papers', 'folder_id',
               existing_type=sa.INTEGER(),
               comment='所属文件夹ID',
               existing_nullable=True)
    op.alter_column('questions', 'folder_id',
               existing_type=sa.INTEGER(),
               comment='所属文件夹ID',
               existing_nullable=True)
    op.add_column('trainings', sa.Column('training_type_id', sa.Integer(), nullable=True, comment='培训班类型ID'))
    op.create_foreign_key(None, 'trainings', 'training_types', ['training_type_id'], ['id'])
    # ### end Alembic commands ###

    # 回填：将已有 trainings.type 字符串映射到 training_types.id
    op.execute(
        "UPDATE trainings SET training_type_id = ("
        "  SELECT id FROM training_types WHERE training_types.code = trainings.type"
        ") WHERE training_type_id IS NULL AND type IS NOT NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'training_type_id')
    op.alter_column('questions', 'folder_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属文件夹ID',
               existing_nullable=True)
    op.alter_column('exam_papers', 'folder_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属文件夹ID',
               existing_nullable=True)
    # ### end Alembic commands ###
