"""add_id_card_number_to_users

Revision ID: e6d38e280503
Revises: 0a9b8c7d6e5f
Create Date: 2026-03-27 15:51:18.218768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6d38e280503'
down_revision: Union[str, None] = '0a9b8c7d6e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_resource_generation_snapshots', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='确认时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_resource_generation_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_resource_generation_snapshots_id'), 'ai_resource_generation_snapshots', ['id'], unique=False)
    op.alter_column('courses', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               comment='文件类型: video/document/image/mixed',
               existing_comment='文件类型: video/document',
               existing_nullable=False)
    op.alter_column('knowledge_points', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('knowledge_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_points', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_constraint('knowledge_points_name_key', 'knowledge_points', type_='unique')
    op.create_index(op.f('ix_knowledge_points_id'), 'knowledge_points', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_name'), 'knowledge_points', ['name'], unique=True)
    op.drop_index('ix_question_knowledge_point_relations_knowledge_point_id', table_name='question_knowledge_point_relations')
    op.add_column('users', sa.Column('id_card_number', sa.String(length=18), nullable=True, comment='身份证号'))
    op.create_index(op.f('ix_users_id_card_number'), 'users', ['id_card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_card_number'), table_name='users')
    op.drop_column('users', 'id_card_number')
    op.create_index('ix_question_knowledge_point_relations_knowledge_point_id', 'question_knowledge_point_relations', ['knowledge_point_id'], unique=False)
    op.drop_index(op.f('ix_knowledge_points_name'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_id'), table_name='knowledge_points')
    op.create_unique_constraint('knowledge_points_name_key', 'knowledge_points', ['name'])
    op.alter_column('knowledge_points', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_points', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('courses', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               comment='文件类型: video/document',
               existing_comment='文件类型: video/document/image/mixed',
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_resource_generation_snapshots_id'), table_name='ai_resource_generation_snapshots')
    op.alter_column('ai_resource_generation_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_resource_generation_snapshots', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='确认时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
