"""make training_id nullable for exams

Revision ID: f4c029187adf
Revises: bbfbefd51a0e
Create Date: 2026-04-02 23:23:24.234035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c029187adf'
down_revision: Union[str, None] = 'bbfbefd51a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='关联培训班ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='关联培训班ID')
    # ### end Alembic commands ###
