"""add_course_qa

Revision ID: f8edba8d885b
Revises: 9b8c7d6e5f4a
Create Date: 2026-03-08 23:57:51.217503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_course_qa

Revision ID: f8edba8d885b
Revises: 9b8c7d6e5f4a
Create Date: 2026-03-08 23:57:51.217503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8edba8d885b'
down_revision: Union[str, None] = '9b8c7d6e5f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)

    if not inspector.has_table('course_qa'):
        op.create_table('course_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='问题内容'),
    sa.Column('answer', sa.Text(), nullable=True, comment='回答内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='提问时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程答疑表'
    )
    op.create_index(op.f('ix_course_qa_id'), 'course_qa', ['id'], unique=False)
    
    # 动态检查并添加考试表的缺失字段（修复由于初始表通过create_all创建导致的增量字段未追踪问题）
    if inspector.has_table('exams'):
        exam_cols = {col['name'] for col in inspector.get_columns('exams')}
        if 'description' not in exam_cols:
            op.add_column('exams', sa.Column('description', sa.Text(), nullable=True, comment='考试描述'))
        if 'duration' not in exam_cols:
            op.add_column('exams', sa.Column('duration', sa.Integer(), server_default='60', comment='考试时长(分钟)'))
        if 'total_score' not in exam_cols:
            op.add_column('exams', sa.Column('total_score', sa.Integer(), server_default='100', comment='总分'))
        if 'passing_score' not in exam_cols:
            op.add_column('exams', sa.Column('passing_score', sa.Integer(), server_default='60', comment='及格分'))
        if 'status' not in exam_cols:
            op.add_column('exams', sa.Column('status', sa.String(length=50), server_default="'upcoming'", comment='状态: active/upcoming/ended'))
        if 'type' not in exam_cols:
            op.add_column('exams', sa.Column('type', sa.String(length=50), server_default="'formal'", comment='类型: formal/quiz'))
        if 'scope' not in exam_cols:
            op.add_column('exams', sa.Column('scope', sa.String(length=200), nullable=True, comment='适用范围'))
        if 'start_time' not in exam_cols:
            op.add_column('exams', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间'))
        if 'end_time' not in exam_cols:
            op.add_column('exams', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间'))
        if 'created_by' not in exam_cols:
            op.add_column('exams', sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True, comment='创建人ID'))
        if 'created_at' not in exam_cols:
            op.add_column('exams', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
        if 'updated_at' not in exam_cols:
            op.add_column('exams', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'))

    if inspector.has_table('exam_records'):
        record_cols = {col['name'] for col in inspector.get_columns('exam_records')}
        if 'result' not in record_cols:
            op.add_column('exam_records', sa.Column('result', sa.String(length=20), nullable=True, comment='结果: pass/fail'))
        if 'grade' not in record_cols:
            op.add_column('exam_records', sa.Column('grade', sa.String(length=5), nullable=True, comment='等级: A/B/C/D'))
        if 'wrong_questions' not in record_cols:
            op.add_column('exam_records', sa.Column('wrong_questions', sa.JSON(), nullable=True, comment='错题列表 [questionId]'))
        if 'dimension_scores' not in record_cols:
            op.add_column('exam_records', sa.Column('dimension_scores', sa.JSON(), nullable=True, comment='维度得分'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_qa_id'), table_name='course_qa')
    op.drop_table('course_qa')
    
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)
    
    if inspector.has_table('exams'):
        exam_cols = {col['name'] for col in inspector.get_columns('exams')}
        if 'type' in exam_cols:
            op.drop_column('exams', 'type')
        if 'scope' in exam_cols:
            op.drop_column('exams', 'scope')
    # 对于其他增量字段可以选择不在 downgrade 中删除，保持稳定
    # ### end Alembic commands ###
