"""add_dashboard_module_configs

Revision ID: ca0be7d27b2f
Revises: e6d38e280503
Create Date: 2026-03-28 09:17:57.743372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0be7d27b2f'
down_revision: Union[str, None] = 'e6d38e280503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_module_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False, comment='模块标识'),
    sa.Column('module_name', sa.String(length=100), nullable=False, comment='模块名称'),
    sa.Column('module_description', sa.Text(), nullable=True, comment='模块描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='模块分类: general/training'),
    sa.Column('visible_role_codes', sa.JSON(), nullable=False, comment='可见角色编码列表'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_module_configs_id'), 'dashboard_module_configs', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_module_configs_module_key'), 'dashboard_module_configs', ['module_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_module_configs_module_key'), table_name='dashboard_module_configs')
    op.drop_index(op.f('ix_dashboard_module_configs_id'), table_name='dashboard_module_configs')
    op.drop_table('dashboard_module_configs')
    # ### end Alembic commands ###
