"""add_course_ids_to_admission_exams

Revision ID: 99fe1ce9722c
Revises: 9e5cca41ad53
Create Date: 2026-04-02 17:24:00.891289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fe1ce9722c'
down_revision: Union[str, None] = '9e5cca41ad53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_exams', sa.Column('course_ids', sa.JSON(), nullable=True, comment='显式绑定课程ID列表'))
    op.add_column('exams', sa.Column('course_ids', sa.JSON(), nullable=True, comment='显式绑定课程ID列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'course_ids')
    op.drop_column('admission_exams', 'course_ids')
    # ### end Alembic commands ###
