"""add training_plans table

Revision ID: 5b9ab54afbd4
Revises: c8d9e0f1a2b3
Create Date: 2026-04-07 13:52:47.577341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ab54afbd4'
down_revision: Union[str, None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_resource_refs', 'library_item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联资源库项ID',
               existing_nullable=True)
    op.alter_column('courses', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               comment='文件类型: video/document/image/audio/knowledge/mixed',
               existing_comment='文件类型: video/document/image/mixed',
               existing_nullable=False)
    op.alter_column('library_items', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否公开到公共资源')
    op.alter_column('question_folders', 'course_id',
               existing_type=sa.INTEGER(),
               comment='关联课程ID（兼容旧数据）',
               existing_nullable=True)
    op.create_foreign_key(None, 'question_folders', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_folders', type_='foreignkey')
    op.alter_column('question_folders', 'course_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联课程ID（兼容旧数据）',
               existing_nullable=True)
    op.alter_column('library_items', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否公开到公共资源')
    op.alter_column('courses', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               comment='文件类型: video/document/image/mixed',
               existing_comment='文件类型: video/document/image/audio/knowledge/mixed',
               existing_nullable=False)
    op.alter_column('course_resource_refs', 'library_item_id',
               existing_type=sa.INTEGER(),
               comment='关联资源库项ID',
               existing_nullable=True)
    # ### end Alembic commands ###
