"""add training course change logs

Revision ID: 48124f7b14b6
Revises: 8738fe0d816a
Create Date: 2026-03-16 17:04:16.732814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48124f7b14b6'
down_revision: Union[str, None] = '8738fe0d816a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_course_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False, comment='培训班ID'),
    sa.Column('course_key', sa.String(length=36), nullable=True, comment='稳定课程键'),
    sa.Column('session_key', sa.String(length=100), nullable=True, comment='课次键'),
    sa.Column('actor_id', sa.Integer(), nullable=True, comment='操作人ID，系统事件为空'),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='对象类型: course/session'),
    sa.Column('action', sa.String(length=30), nullable=False, comment='动作: create/update/delete/status_change'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='来源: detail_update/import_schedule/system_refresh 等'),
    sa.Column('batch_id', sa.String(length=36), nullable=False, comment='同一次操作批次号'),
    sa.Column('course_name', sa.String(length=200), nullable=True, comment='课程名快照'),
    sa.Column('session_label', sa.String(length=200), nullable=True, comment='课次标签快照'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='变更摘要'),
    sa.Column('before_json', sa.JSON(), nullable=True, comment='变更前快照'),
    sa.Column('after_json', sa.JSON(), nullable=True, comment='变更后快照'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_course_change_logs_actor_id'), 'training_course_change_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_training_course_change_logs_batch_id'), 'training_course_change_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_course_change_logs_course_key'), 'training_course_change_logs', ['course_key'], unique=False)
    op.create_index(op.f('ix_training_course_change_logs_id'), 'training_course_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_training_course_change_logs_session_key'), 'training_course_change_logs', ['session_key'], unique=False)
    op.create_index('ix_training_course_change_logs_training_created', 'training_course_change_logs', ['training_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_training_course_change_logs_training_id'), 'training_course_change_logs', ['training_id'], unique=False)
    op.add_column('training_courses', sa.Column('course_key', sa.String(length=36), nullable=True, comment='稳定课程键'))
    op.create_index(op.f('ix_training_courses_course_key'), 'training_courses', ['course_key'], unique=False)
    op.create_unique_constraint('uq_training_course_key', 'training_courses', ['training_id', 'course_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_training_course_key', 'training_courses', type_='unique')
    op.drop_index(op.f('ix_training_courses_course_key'), table_name='training_courses')
    op.drop_column('training_courses', 'course_key')
    op.drop_index(op.f('ix_training_course_change_logs_training_id'), table_name='training_course_change_logs')
    op.drop_index('ix_training_course_change_logs_training_created', table_name='training_course_change_logs')
    op.drop_index(op.f('ix_training_course_change_logs_session_key'), table_name='training_course_change_logs')
    op.drop_index(op.f('ix_training_course_change_logs_id'), table_name='training_course_change_logs')
    op.drop_index(op.f('ix_training_course_change_logs_course_key'), table_name='training_course_change_logs')
    op.drop_index(op.f('ix_training_course_change_logs_batch_id'), table_name='training_course_change_logs')
    op.drop_index(op.f('ix_training_course_change_logs_actor_id'), table_name='training_course_change_logs')
    op.drop_table('training_course_change_logs')
    # ### end Alembic commands ###
