"""allow null assignee and actor for ai review

Revision ID: 1dfb8ab36d03
Revises: 3713f097bab0
Create Date: 2026-04-09 15:56:12.960551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfb8ab36d03'
down_revision: Union[str, None] = '3713f097bab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='操作人ID，AI审核时为NULL')
    op.alter_column('review_logs', 'action',
               existing_type=sa.VARCHAR(length=30),
               comment='动作: submit/approve/reject/revoke/reassign/ai_fallback',
               existing_comment='动作: submit/approve/reject/revoke/reassign',
               existing_nullable=False)
    op.alter_column('review_tasks', 'assignee_user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='审核人ID，AI审核时为NULL',
               existing_comment='审核人ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_tasks', 'assignee_user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='审核人ID',
               existing_comment='审核人ID，AI审核时为NULL')
    op.alter_column('review_logs', 'action',
               existing_type=sa.VARCHAR(length=30),
               comment='动作: submit/approve/reject/revoke/reassign',
               existing_comment='动作: submit/approve/reject/revoke/reassign/ai_fallback',
               existing_nullable=False)
    op.alter_column('review_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='操作人ID，AI审核时为NULL')
    # ### end Alembic commands ###
