"""add_permission_groups_table

Revision ID: bbfbefd51a0e
Revises: 99fe1ce9722c
Create Date: 2026-04-02 22:32:14.987875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfbefd51a0e'
down_revision: Union[str, None] = '99fe1ce9722c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=100), nullable=False, comment='权限组标识'),
    sa.Column('group_name', sa.String(length=100), nullable=False, comment='权限组名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限组描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_groups_group_key'), 'permission_groups', ['group_key'], unique=True)
    op.create_index(op.f('ix_permission_groups_id'), 'permission_groups', ['id'], unique=False)
    op.add_column('permissions', sa.Column('group_id', sa.Integer(), nullable=True, comment='所属权限组'))
    op.alter_column('permissions', 'group',
               existing_type=sa.VARCHAR(length=100),
               comment='权限分组标识（冗余，与 group_key 一致）',
               existing_comment='权限分组',
               existing_nullable=False,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.create_foreign_key(None, 'permissions', 'permission_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.alter_column('permissions', 'group',
               existing_type=sa.VARCHAR(length=100),
               comment='权限分组',
               existing_comment='权限分组标识（冗余，与 group_key 一致）',
               existing_nullable=False,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.drop_column('permissions', 'group_id')
    op.drop_index(op.f('ix_permission_groups_id'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_group_key'), table_name='permission_groups')
    op.drop_table('permission_groups')
    # ### end Alembic commands ###
