"""add_training_visibility_scope

Revision ID: 209e778b7e3f
Revises: ca0be7d27b2f
Create Date: 2026-03-30 16:31:41.284023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209e778b7e3f'
down_revision: Union[str, None] = 'ca0be7d27b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('visibility_scope', sa.String(length=30), nullable=True, comment='可见范围: all/department/department_and_sub'))
    op.add_column('trainings', sa.Column('visibility_department_ids', sa.JSON(), nullable=True, comment='可见部门ID列表，visibility_scope非all时生效'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'visibility_department_ids')
    op.drop_column('trainings', 'visibility_scope')
    # ### end Alembic commands ###
